
//USER 

//Register Applicant
export const REGISTER_APPLICANT_REQUEST = 'REGISTER_APPLICANT_REQUEST';
export const REGISTER_APPLICANT_SUCCESS = 'REGISTER_APPLICANT_SUCCESS';
export const REGISTER_APPLICANT_FAIL = 'REGISTER_APPLICANT_FAIL';

//Register Recruiter
export const REGISTER_RECRUITER_REQUEST = 'REGISTER_RECRUITER_REQUEST';
export const REGISTER_RECRUITER_SUCCESS = 'REGISTER_RECRUITER_SUCCESS';
export const REGISTER_RECRUITER_FAIL = 'REGISTER_RECRUITER_FAIL';


//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//LOGUT 
export const LOGOUT = 'LOGOUT';

//GET PROFILE
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

//Update Applicant
export const UPDATE_APPLICANT_REQUEST = 'UPDATE_APPLICANT_REQUEST';
export const UPDATE_APPLICANT_SUCCESS = 'UPDATE_APPLICANT_SUCCESS';
export const UPDATE_APPLICANT_FAIL= 'UPDATE_APPLICANT_FAIL';

//UPDATE Recruiter
export const UPDATE_RECRUITER_REQUEST = 'UPDATE_RECRUITER_REQUEST';
export const UPDATE_RECRUITER_SUCCESS = 'UPDATE_RECRUITER_SUCCESS';
export const UPDATE_RECRUITER_FAIL= 'UPDATE_RECRUITER_FAIL';

//Job
export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAIL = 'GET_JOBS_FAIL';

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL'

//get job by id
export const GET_JOB_BY_ID_REQUEST = 'GET_JOB_BY_ID_REQUEST'
export const GET_JOB_BY_ID_SUCCESS = 'GET_JOB_BY_ID_SUCCESS'
export const GET_JOB_BY_ID_FAIL = 'GET_JOB_BY_ID_FAIL'
//edit
export const EDIT_JOB_REQUEST = 'EDIT_JOB_REQUEST'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_FAIL = 'EDIT_JOB_FAIL'

//Recruiter create exam
export const CREATE_EXAM_REQUEST = 'CREATE_EXAM_REQUEST'
export const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS'
export const CREATE_EXAM_FAIL = 'CREATE_EXAM_FAIL'

//get available exams
export const GET_EXAMS_REQUEST= 'GET_EXAM_REQUEST'
export const GET_EXAMS_SUCCESS = 'GET_EXAMS_SUCCESS'
export const GET_EXAMS_FAIL = 'GET_EXAMS_FAIL'

//pick exam from available exams
export const PICK_EXAM_REQUEST = 'PICK_EXAM_REQUEST'
export const PICK_EXAM_SUCCESS = 'PICK_EXAM_SUCCESS'
export const PICK_EXAM_FAIL = 'PICK_EXAM_FAIL'

//get exams for certain job
export const GET_JOB_EXAMS_REQUEST = 'GET_JOB_EXAMS_REQUEST'
export const GET_JOB_EXAMS_SUCCESS = 'GET_JOB_EXAMS_SUCCESS'
export const GET_JOB_EXAMS_FAIL = 'GET_JOB_EXAMS_FAIL'

//assign task to applicants
export const ASSIGN_TASK_TO_APPLICANTS_REQUEST = 'ASSIGN_TASK_TO_APPLICANTS_REQUEST'
export const ASSIGN_TASK_TO_APPLICANTS_SUCCESS = 'ASSIGN_TASK_TO_APPLICANTS_SUCCESS'
export const ASSIGN_TASK_TO_APPLICANTS_FAIL = 'ASSIGN_TASK_TO_APPLICANTS_FAIL'


export const CHOOSE_CATEGORY_REQUEST='CHOOSE_CATEGORY_REQUEST'
export const CHOOSE_CATEGORY_SUCCESS='CHOOSE_CATEGORY_SUCCESS'
export const CHOOSE_CATEGORY_FAIL='CHOOSE_CATEGORY_FAIL'



export const CHOOSE_TOPIC_REQUEST='CHOOSE_TOPIC_REQUEST'
export const CHOOSE_TOPIC_SUCCESS='CHOOSE_TOPIC_SUCCESS'
export const CHOOSE_TOPIC_FAIL='CHOOSE_TOPIC_FAIL'



export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST'
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL'

