
//USER 

//Register Applicant
export const REGISTER_APPLICANT_REQUEST = 'REGISTER_APPLICANT_REQUEST';
export const REGISTER_APPLICANT_SUCCESS = 'REGISTER_APPLICANT_SUCCESS';
export const REGISTER_APPLICANT_FAIL = 'REGISTER_APPLICANT_FAIL';

//Register Recruiter
export const REGISTER_RECRUITER_REQUEST = 'REGISTER_RECRUITER_REQUEST';
export const REGISTER_RECRUITER_SUCCESS = 'REGISTER_RECRUITER_SUCCESS';
export const REGISTER_RECRUITER_FAIL = 'REGISTER_RECRUITER_FAIL';


//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//LOGUT 
export const LOGOUT = 'LOGOUT';

//Update Applicant
export const UPDATE_APPLICANT_REQUEST = 'UPDATE_APPLICANT_REQUEST';
export const UPDATE_APPLICANT_SUCCESS = 'UPDATE_APPLICANT_SUCCESS';
export const UPDATE_APPLICANT_FAIL= 'UPDATE_APPLICANT_FAIL';

//UPDATE Recruiter
export const UPDATE_RECRUITER_REQUEST = 'UPDATE_RECRUITER_REQUEST';
export const UPDATE_RECRUITER_SUCCESS = 'UPDATE_RECRUITER_SUCCESS';
export const UPDATE_RECRUITER_FAIL= 'UPDATE_RECRUITER_FAIL';



